# Generated by Django 5.0.1 on 2024-01-25 22:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
