# Generated by Django 4.2.7 on 2024-07-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_api', '0003_alter_document_options_document_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_id',
            field=models.CharField(default='testid', max_length=240, verbose_name='FileId'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='vector_id',
            field=models.CharField(default='vector', max_length=240, verbose_name='VectorId'),
            preserve_default=False,
        ),
    ]
