# Generated by Django 5.0.1 on 2024-01-25 22:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extension_api', '0001_initial'),
        ('keyword_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=240, verbose_name='Description')),
                ('signature', models.BooleanField()),
                ('type', models.CharField(max_length=240, verbose_name='Type')),
                ('created', models.DateField(auto_now_add=True)),
                ('extensions', models.ManyToManyField(to='extension_api.extension')),
                ('keywords', models.ManyToManyField(to='keyword_api.keyword')),
            ],
        ),
    ]
