# Generated by Django 5.0.6 on 2024-07-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_api', '0001_initial'),
        ('extension_api', '0001_initial'),
        ('keyword_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='extensions',
            field=models.ManyToManyField(blank=True, to='extension_api.extension'),
        ),
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='keyword_api.keyword'),
        ),
    ]
