apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-web
  template:
    metadata:
      labels:
        app: ai-web
    spec:
      containers:
      - name: ai-web
        image: 058264311571.dkr.ecr.eu-west-3.amazonaws.com/ekasan-ai-repository:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: scripts
          mountPath: /app/scripts
        command: ["/bin/sh", "-c", "cd main && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
      volumes:
      - name: scripts
        configMap:
          name: web-scripts-config
