# Generated by Django 4.2.2 on 2023-07-03 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=240, verbose_name='Document Type')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('tool', models.DateField(auto_now_add=True)),
                ('keywords', models.JSONField(verbose_name='keywords')),
            ],
        ),
    ]
