version: "3"
services:
  pgdb:
    image: postgres:14
    restart: always
    volumes:
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - type: volume
        source: pgdb-data
        target: "/var/lib/postgresql/data"

    networks:
      - ekasan-docker-network
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_PASSWORD: ekasan_secure_password
      POSTGRES_USER: ekasan_user
      POSTGRES_DB: ekasan_db_renew
  # ai-db:
  #   image: postgres:14
  #   restart: always
  #   volumes:
  #     - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  #     - type: volume
  #       source: pgdb-data
  #       target: "/var/lib/postgresql/data"

  #   networks:
  #     - ekasan-docker-network
  #   ports:
  #     - "0.0.0.0:5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: ekasan_secure_password
  #     POSTGRES_USER: ekasan_user
  #     POSTGRES_DB: ekasan_db_renew
  web:
    build:
      context: .
    networks:
      - ekasan-docker-network
    volumes:
      - ./:/app/
    ports:
      - "8090:8090"
    depends_on:
      pgdb:
        condition: service_started
    command: sh -c "python scripts/is_db_ready.py && scripts/create_auth.sh"
  localstack:
    image: localstack/localstack:2.0
    ports:
      - '0.0.0.0:4566:4566' # LocalStack endpoint
      - '0.0.0.0:4510-4559:4510-4559' # external services port range
    networks:
      - ekasan-docker-network
    volumes:
      - "./localstack-script/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - '/var/run/docker.sock:/var/run/docker.sock'

  ai_web:
    env_file:
      - ./ai_api/.env
    build:
      context: .
    networks:
      - ekasan-docker-network
    volumes:
      - ./:/app/
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      web:
        condition: service_started
    # Replace in scripts/create_auth if needed to prevent multiple api key.
    # ./scripts/store_cred.sh 'OPENAI_API_KEY' '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' &&
    command: sh -c "
        python ai_api/manage.py migrate &&
        python ai_api/manage.py runserver 0.0.0.0:8000"
  
volumes:
  eksan-volume:
  pgdb-data: 
networks:
  ekasan-docker-network:
