apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgdb
  template:
    metadata:
      labels:
        app: pgdb
    spec:
      containers:
      - name: pgdb
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_PASSWORD
          value: ekasan_secure_password
        - name: POSTGRES_USER
          value: ekasan_user
        - name: POSTGRES_DB
          value: ekasan_db_renew
        volumeMounts:
        - name: pgdb-data
          mountPath: /var/lib/postgresql/data  # Utiliser un sous-répertoire
          subPath: pgdata
        - name: init-db
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: pgdb-data
        persistentVolumeClaim:
          claimName: pgdb-data-pvc
      - name: init-db
        configMap:
          name: init-db-config
